
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS org_users;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS servervideo;
DROP TABLE IF EXISTS video;
DROP TABLE IF EXISTS videofolder;
DROP TABLE IF EXISTS videoimage;
DROP TABLE IF EXISTS org;